apiVersion: "stable.couchdb.org/v1"
kind: CouchDB
metadata:
  name: my-couchdb-cluster
  namespace: default
spec:
  version: "2.1.0"
  baseImage:   "nicolai86/couchdb"
  size: 3
  pod: 
    labels:
      app: couchdb
    nodeSelector:
      app: couchdb
    antiAffinity: false
    couchdbEnv:
      - { name: COUCHDB_USER, value: admin }
      - { name: COUCHDB_PASSWORD, value: admin }
      # - { name: COUCHDB_PASSWORD, valueFrom: { configMapRef: { name: couchdb-config-map, key: username } } }
      # - { name: COUCHDB_PASSWORD, valueFrom: { secretKeyRef: { name: couchdb-secret, key: username } } }
---
kind: Service
apiVersion: v1
metadata:
  name: couchdb
spec:
  selector:
    cluster: my-couchdb-cluster
    app: couchdb
  ports:
  - protocol: TCP
    port: 5984
    name: "standalone"
    targetPort: 5984
    nodePort: 31984
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config-map
  namespace: default
data:
  password: admin-configmap
---
apiVersion: v1
kind: Secret
metadata:
  name: couchdb-secret
  namespace: default
data:
  password: YWRtaW4tc2VjcmV0bWFw # admin-secretmap
