apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: couchdb-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: couchdb-operator
    spec:
      containers:
      - name: couchdb-operator
        image: nicolai86/couchdb-operator:v0.0.1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
