apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: couchdb-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: couchdb-operator
    spec:
      serviceAccountName: couchdb-operator
      containers:
      - name: couchdb-operator
        image: nicolai86/couchdb-operator:v0.0.2
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: couchdb-operator
  namespace: default
automountServiceAccountToken: true
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: couchdb-operator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["stable.couchdb.org"]
    resources: ["couchdbs"]
    verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: couchdb-operators
  namespace: default
subjects:
  - kind: ServiceAccount
    name: couchdb-operator
    namespace: default
roleRef:
  kind: Role
  name: couchdb-operator
  apiGroup: rbac.authorization.k8s.io